# Generated by Django 5.0.6 on 2024-06-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ticket_ref_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ref_no',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
