# Generated by Django 5.0.6 on 2024-06-20 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ticket_ref_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booking_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
