# Generated by Django 5.0.6 on 2024-06-20 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_ticket_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booking_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
