# Generated by Django 5.0.6 on 2024-06-20 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ticket_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
