const flightsList = [
    {
        company : 'Indigo',
        code : '6E',
        departTime : '10:00 AM',
        arrivalTime : '12:00 PM',
        Price : '₹ 5000',
        from : 'Delhi',
        to : 'Mumbai',
        duration : '2 h 10m',
    },
    {
        company: 'Air India',
        code: 'AI',
        departTime: '08:30 AM',
        arrivalTime: '10:45 AM',
        Price: '₹ 4500',
        from: 'Delhi',
        to: 'Kolkata',
        duration: '2 h 15m',
    },
    {
        company: 'SpiceJet',
        code: 'SG',
        departTime: '02:15 PM',
        arrivalTime: '04:30 PM',
        Price: '₹ 3500',
        from: 'Mumbai',
        to: 'Chennai',
        duration: '2 h 15m',
    },
    {
        company: 'GoAir',
        code: 'G8',
        departTime: '06:45 AM',
        arrivalTime: '09:00 AM',
        Price: '₹ 4000',
        from: 'Delhi',
        to: 'Bengaluru',
        duration: '2 h 15m',
    },
    {
        company: 'Vistara',
        code: 'UK',
        departTime: '11:30 AM',
        arrivalTime: '01:45 PM',
        Price: '₹ 5500',
        from: 'Chennai',
        to: 'Delhi',
        duration: '2 h 15m',
    },
    {
        company: 'AirAsia',
        code: 'AK',
        departTime: '03:00 PM',
        arrivalTime: '05:15 PM',
        Price: '₹ 3000',
        from: 'Kolkata',
        to: 'Mumbai',
        duration: '2 h 15m',
    },
    {
        company: 'Jet Airways',
        code: '9W',
        departTime: '07:30 AM',
        arrivalTime: '09:45 AM',
        Price: '₹ 6000',
        from: 'Bengaluru',
        to: 'Delhi',
        duration: '2 h 15m',
    },
    {
        company: 'Air India',
        code: 'AI',
        departTime: '12:15 PM',
        arrivalTime: '02:30 PM',
        Price: '₹ 5000',
        from: 'Delhi',
        to: 'Chennai',
        duration: '2 h 15m',
    },
    {
        company: 'IndiGo',
        code: '6E',
        departTime: '04:45 PM',
        arrivalTime: '07:00 PM',
        Price: '₹ 4000',
        from: 'Mumbai',
        to: 'Delhi',
        duration: '2 h 15m',
    },
    {
        company: 'SpiceJet',
        code: 'SG',
        departTime: '09:30 AM',
        arrivalTime: '11:45 AM',
        Price: '₹ 3500',
        from: 'Delhi',
        to: 'Kolkata',
        duration: '2 h 15m',
    },
    {
        company: 'GoAir',
        code: 'G8',
        departTime: '01:00 PM',
        arrivalTime: '03:15 PM',
        Price: '₹ 4000',
        from: 'Chennai',
        to: 'Mumbai',
        duration: '2 h 15m',
    },
    {
        company: 'Vistara',
        code: 'UK',
        departTime: '05:30 PM',
        arrivalTime: '07:45 PM',
        Price: '₹ 5500',
        from: 'Delhi',
        to: 'Bengaluru',
        duration: '2 h 15m',
    },
    {
        company: 'AirAsia',
        code: 'AK',
        departTime: '10:15 AM',
        arrivalTime: '12:30 PM',
        Price: '₹ 3000',
        from: 'Mumbai',
        to: 'Chennai',
        duration: '2 h 15m',
    },
    {
        company: 'Jet Airways',
        code: '9W',
        departTime: '02:45 PM',
        arrivalTime: '05:00 PM',
        Price: '₹ 6000',
        from: 'Kolkata',
        to: 'Delhi',
        duration: '2 h 15m',
    },
    {
        company: 'Air India',
        code: 'AI',
        departTime: '07:30 AM',
        arrivalTime: '09:45 AM',
        Price: '₹ 5000',
        from: 'Bengaluru',
        to: 'Mumbai',
        duration: '2 h 15m',
    },
    {
        company: 'IndiGo',
        code: '6E',
        departTime: '12:00 PM',
        arrivalTime: '02:15 PM',
        Price: '₹ 4000',
        from: 'Delhi',
        to: 'Kolkata',
        duration: '2 h 15m',
    },
    {
        company: 'SpiceJet',
        code: 'SG',
        departTime: '04:30 PM',
        arrivalTime: '06:45 PM',
        Price: '₹ 3500',
        from: 'Mumbai',
        to: 'Chennai',
        duration: '2 h 15m',
    }
]